- hosts: localhost
  tasks:
    - include_vars: "{{ playbook_dir }}/vars.yml"
    - include_vars: "{{ playbook_dir }}/magma_config.yml"
    - name: Wait for connection
      wait_for:
        host: "{{ item }}"
        port: 22
        timeout: 3000
      loop:
        "{{ all }}"

    - name: Clear files directory
      file:
        path: "{{ playbook_dir }}/files"
        state: absent

    - name: Create files directory
      file:
        path: "{{ playbook_dir }}/files"
        state: directory     
  
    - name: Create domain file
      shell: |
        echo {{ domain }} > {{ playbook_dir }}/domain.txt
  
    - name: Create namespace file
      shell: |
        echo {{ namespace }} > {{ playbook_dir }}/namespace.txt

          
- hosts: BASTIAN
  user: debian
  become: false
  roles:
    - role: 01-update
      when: orc8r|default(false)|bool == true
    - role: 02-image_builder
      when: build_images|default(false)|bool == true
    - role: 03-build_orchestrator
      when: build_images|default(false)|bool == true 
    - role: 04-upload_images
      when: build_images|default(false)|bool == true 
    - role: 05-deploy 
      when: orc8r|default(false)|bool == true
    - role: 07-get_certs
      when: orc8r|default(false)|bool == true
 
