- hosts: localhost
  tasks:
    - include_vars: "{{ playbook_dir }}/vars.yml"
    - include_vars: "{{ playbook_dir }}/magma_config.yml"
    - name: Wait for connection
      wait_for:
        host: "{{ item }}"
        port: 22
        timeout: 3000
      loop:
        "{{ all }}"

    - name: Clear files directory
      file:
        path: "{{ playbook_dir }}/files"
        state: absent

    - name: Create files directory
      file:
        path: "{{ playbook_dir }}/files"
        state: directory     
  
    - name: Create domain file
      shell: |
        echo {{ domain }} > {{ playbook_dir }}/domain.txt
  
    - name: Create namespace file
      shell: |
        echo {{ namespace }} > {{ playbook_dir }}/namespace.txt

- hosts: AGW
  user: ubuntu
  become: true
  roles:
    - role: 06-check-agw
      when: agw|default(false)|bool == true
    - role: 08-configure_agw
      when: agw|default(false)|bool == true
