- hosts: localhost
  tasks:
    - include_vars: "{{ playbook_dir }}/vars.yml"
    - include_vars: "{{ playbook_dir }}/magma_config.yml"
    - name: Wait for connection
      wait_for:
        host: "{{ item }}"
        port: 22
        timeout: 3000
      loop:
        "{{ all }}"  
  
    - name: Create domain file
      shell: |
        echo {{ domain }} > {{ playbook_dir }}/domain.txt
  
    - name: Create namespace file
      shell: |
        echo {{ namespace }} > {{ playbook_dir }}/namespace.txt

- hosts: AGW
  user: ubuntu
  become: true
  roles:
    - role: 10-integrate_agw
      when: agw|default(false)|bool == true
