- hosts: localhost
  tasks:
    - include_vars: "{{ playbook_dir }}/vars.yml"
    - include_vars: "{{ playbook_dir }}/magma_config.yml"
    - name: Wait for connection
      wait_for:
        host: "{{ item }}"
        port: 22
        timeout: 3000
      loop:
        "{{ all }}"

- hosts: BASTIAN
  user: debian
  become: false
  roles:
    - role: 07-get_certs


    
