apiVersion: v1
kind: Service
metadata:
  name: fluentd
  labels:
    app: fluentd
spec:
  ports:
    - name: "24224"
      port: 24224
      targetPort: 24224
    - name: "24225"
      port: 24225
      targetPort: 24225
  selector:
    app: fluentd
  type: LoadBalancer
status:
  loadBalancer: {}
