---
# tasks file for 01-update 
  - include_vars: "{{ playbook_dir }}/vars.yml" 
  - include_vars: "{{ playbook_dir }}/magma_config.yml" 
  - include_vars: "{{ playbook_dir }}/names.yml" 

  - name: Get hostname
    shell: hostname
    register: hname

  - name: Configure /etc/hosts
    template:
      src: hosts.j2
      dest: /etc/hosts
        
  - name: Restart magma service
    shell: |
      service magma@* stop
      service magma@magmad restart

  - name: Wait until services are running      
    shell: |        
      if [ `/usr/bin/systemctl | grep -P '\s+magma.*\s+loaded\sactive\srunning\s+' | wc -l` -lt 15 ]; then 
        exit 1
      fi
    register: svc
    retries: 100
    delay: 10
    until: svc is success  
    
  - name: Reboot
    reboot:
      msg: Reboot triggered
      reboot_timeout: 360
  - name: Wait until services are running      
    shell: |        
      if [ `/usr/bin/systemctl | grep -P '\s+magma.*\s+loaded\sactive\srunning\s+' | wc -l` -lt 15 ]; then 
        exit 1
      fi
    register: svc
    retries: 100
    delay: 10
    until: svc is success  



      