# Default values for logging-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fluentd:
  image:
    repository: registry.kube.int/magma/orc8r-fluentd
    tag: 1.8.0
    imagePullSecret: orc8r-secrets-registry 
      