---
# tasks file for 01-update 
  - name: Wait for installation
    become: true
    wait_for:
      path: /root/installation_finished
      timeout: 7200

  - name: Reboot
    become: true
    reboot:
      msg: Reboot triggered
      reboot_timeout: 3600

      