apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: fluentd
  name: fluentd
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fluentd
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: fluentd
    spec:
      containers:
      - image: fluentd
        imagePullPolicy: ""
        name: fluentd
        ports:
        - containerPort: 24224
        - containerPort: 24224
          protocol: UDP
        - containerPort: 24225
        - containerPort: 24225
          protocol: UDP
        resources: {}        
        volumeMounts:
        - mountPath: /etc/fluent/config.d
          name: config-volume-fluentd
        - mountPath: /var/log/fluentd-buffers
          name: buffer
        - mountPath: /certs
          name: certs
          readOnly: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - configMap:
          defaultMode: 511
          name: fluentd
        name: config-volume-fluentd
      - emptyDir: {}
        name: buffer
      - name: certs
        secret:
          defaultMode: 420
          secretName: fluentd-certs